### ISSUE TITLE
Multiple errors when ending an experiment in the SPOT GUI

### ISSUE THREAD

**Issue by natashadawnn** [Carleton-SRCL/SPOT#61] opened 2024-01-15 19:10 UTC
Running experiments today and noticed that multiple errors popped up in the command window when the "Stop Experiment" button was pressed. It does not seem to affect anything, but looks like there is a bug.

![image](https://github.com/Carleton-SRCL/SPOT/assets/144704761/f3a021f1-aa9f-4734-868c-b87f28f00232)

Logs:
~~~
Note: For the complete log, run the following command in the MATLAB command window:
system(hwobj,'cat /home/spot-blue/ExperimentSoftware/MATLAB_ws/R2023a/C/Users/SPOT/Documents/SPOT-4.0.0-RC.4_-_APF/SPOT-4.0.0-RC.4/SPOT-4.0.0-RC.4/Projects/APF_Path_Planning_Revised/APF_Path_Planning_2023a.log')
Checking connection to RED platform...
Checking connection to BLACK platform...
Checking connection to BLUE platform...
SUCCESS: The process "StreamData.exe" with PID 18576 has been terminated.
Dot indexing is not supported for variables of this type.

Error in GUI_v4_0_Main/StartSimulationButtonPushed (line 2012)
            dataPacket = simOut.dataPacket;

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
~~~

Will be running more experiments tomorrow so I can add more detail to this ticket if necessary.

**Comment by TheElectricDream** [comment] 2024-01-15 19:51
That looks like someone tried to save simulation data (hence the dataPacket = simOut.dataPacket), but no simulation data exists. 

Please document the exact steps needed to replicate this error and I will investigate.

**Comment by TheElectricDream** [comment] 2024-01-17 02:45
After some digging around, the problem was resolved by copying the contents from the problematic Simulink diagram to a fresh copy of the template diagram from RC.4. It appears the problem is isolated to this one copy, and the most likely cause is that the Simulink diagram was tweaked in MATLAB 2023b and then ported to 2023a.

I am closing this issue. If the problem reappears, I will reopen this issue.

**Closed by TheElectricDream** 2024-01-17 02:45 UTC
